version: "3.10.4"
services:
  worker:
    build: .
    environment:
      BOT_TOKEN: $BOT_TOKEN
      API_ID: $API_ID
      API_HASH: $API_HASH
      OWNER_ID: $OWNER_ID
      DATABASE_URL: $DATABASE_URL
